routes/web.php
<?php

use App\Models\Game;
use App\Models\User;
use Illuminate\Support\Facades\Route;
use App\Http\Resources\GameCollection;
use App\Manager\CharacteristicManager;
use App\Http\Controllers\GameController ;
use App\Http\Controllers\ExpressionController;
use App\Http\Controllers\WordController;
use App\Http\Controllers\PictureController;
use App\Http\Controllers\ParametersController ;
use App\Http\Controllers\DematerializedGamesController ;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('accueil', [
        
    ]);
})->name('accueil');

Route::get('/dashboard', function () {
    //return Redirect::route('');
    return redirect()->route('games.index');
})->name('dashboard');

/* ---------------------- Membres connectés ---------------------- */
Route::get('/profile', [ParametersController::class, 'userProfile'])->middleware(['auth'])->name('userProfile');
Route::put('/profile', [ParametersController::class, 'updateProfile'])->middleware(['auth'])->name('updateUserProfile');

//jeux dématérialisés
Route::get('/dematerialized-games/lynx', [DematerializedGamesController::class, 'lynx'])->name('dematerialized-games.lynx');

Route::get('/dematerialized-games/vocabulangue', [DematerializedGamesController::class, 'vocalang'])->name('dematerialized-games.vocalang');
Route::get('/dematerialized-games/vocabulangue/{language_iso}/{chosenLanguage_iso}', [DematerializedGamesController::class, 'chosenVocalang'])->where('language_iso', '[A-Za-z]+')->where('chosenLanguage_iso', '[A-Za-z]+')->name('dematerialized-games.chosenVocalang');

Route::resources([
    'games'         => GameController::class,
    'expressions'   => ExpressionController::class,
    'words'         => WordController::class,
    'pictures'      => PictureController::class,
]);

/* ---------------------- Zone ADMIN ---------------------- */


Route::prefix('admin')->middleware(['auth_admin'])->group(function () {
    Route::get('/administration', [ParametersController::class, 'administration'])->name('admin.administration');
    Route::get('/expressions', [ParametersController::class, 'administrateExpressions'])->name('admin.expressions');
});



require __DIR__.'/auth.php';

app/Models/Game.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Game extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'games';

    protected $fillable = [
        'user_id_borrower',
        'title',
        'slug',
        'shortdescription',
        'affrontementtype',
        'capacityneeded',
        'type',
        'format',
        'durationgame',
        'is_gamemasterneeded',
        'nbplayers_min',
        'nbplayers_max',
        'minimalage',
        'content',
        'rules_text',
        'rules_video',
        'illustration',
        'externalborrower_name',
        'is_available',
        'deleted_at'
    ] ;

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true ;

    /**
     * The users that get the game.
     */
    public function owners() {

        return $this->belongsToMany(User::class, 'game_user');

    }
}

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Models\Game;
use App\Models\User;

use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Models\Characteristic;
use App\Http\Requests\GameRequest;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Manager\CharacteristicManager;

class GameController extends Controller {

    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct() {
        //$this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     * @param  Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {

        /*//get user's games
        $user = Auth::user() ;
        $games = $user->games()->orderBy('title')->get() ;

        return view('game.list', [
            'games' => $games
        ]);*/

        

        $sqlWhereConditions = [['games.is_available', '=', '1']] ;

        //si on a reçu des paramètres de recherche, on ajoute les critères à la requête SQL en préparation
        if(!empty($request->all())) {
            if(!empty(request("game_title"))) {
                $sqlWhereConditions[] = ['title','LIKE','%'.request("game_title").'%'] ;
            }
    
            if(!empty(request("game_nbPlayers"))) {
                $sqlWhereConditions[] = ['nbplayers_min','<=',request("game_nbPlayers")] ;
                $sqlWhereConditions[] = ['nbplayers_max','>=',request("game_nbPlayers")] ;
            }
    
            if(!empty(request("format"))) {
                $sqlWhereConditions[] = ['format','=',request("format")] ;
            }
            if(!empty(request("affrontementtype"))) {
                $sqlWhereConditions[] = ['affrontementtype','=',request("affrontementtype")] ;
            }
            if(!empty(request("type"))) {
                $sqlWhereConditions[] = ['type','=',request("type")] ;
            }
            /*
            if(!empty(request("capacityneeded"))) {
                $sqlWhereConditions[] = ['capacityneeded','LIKE','%'.request("capacityneeded").'%'] ;
            }*/
        }

        //si l'user a demandé la liste de ses jeux, on fera une jointure
        if(!empty(request("onlyMyGames"))) {
            $userId = Auth::user()->id ;

            $games = DB::table('games')
                ->join('game_user', 'games.id', '=', 'game_user.game_id')
                ->where($sqlWhereConditions)
                ->where('game_user.user_id', '=', $userId)
                ->orderBy('title')
                ->get();
        } else {
            $games = DB::table('games')->where($sqlWhereConditions)->orderBy('title')->get();
        }

        $characteristicsManager = new CharacteristicManager ;

        return view('game.list', [
            'games'                     => $games,
            'searchParameters'          => $request->all(),
            'users_byId'                => User::select(['id', 'name'])->orderBy('id')->get()->keyBy('id'),
            'gameTypesList'             => $characteristicsManager->getTypesList(),
            'gameAffrontementsList'     => $characteristicsManager->getAffrontementsList(),
            'gameFormatsList'           => $characteristicsManager->getFormatsList(),
            'gameCapacitesList'         => $characteristicsManager->getCapacitesList(),
        ]);
    }

    /**
     * Display a form to create a newly resource in storage.
     *
     * @return \Illuminate\Http\Response
     */

    public function create()
    {
        $characteristicsManager = new CharacteristicManager ;
        
        return view('game.create', [
            'gameTypesList'             => $characteristicsManager->getTypesList(),
            'gameAffrontementsList'     => $characteristicsManager->getAffrontementsList(),
            'gameFormatsList'           => $characteristicsManager->getFormatsList(),
            'gameCapacitesList'         => $characteristicsManager->getCapacitesList(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\GameRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GameRequest $request) {
        if (!Auth::check()) {
            dd("Vous êtes déconnecté·e, cette page n'est pas disponible");
        }
        
        $userId = Auth::id() ;

        $validatedData = $request->validated() ;
        $validatedData['user_id_owner'] = $userId ;
        
        //isMethod('GET')
        
        //$request->all()
        //$request->input('monChamp')
        //$request->missing('monChamp')
        
        if($request->hasFile('file')) {
            // Upload file
            $file = $request->file;
            $filename = Str::slug($validatedData['title'], '_') . '.' . $file->extension() ;
            $location = 'img/games_covers/';
            $file->move($location,$filename);

            $validatedData['illustration'] = $filename ;
        }

        $theGame = Game::create($validatedData);

        return redirect()->route('games.index')->with('success', 'Le jeu a bien été ajouté');
    }

    /**
     * Display the specified resource.
     *
     * @param  string  $slug
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $game = Game::where('slug', $slug)->get()->first() ;

        if(is_null($game)) {
            return redirect()->route('games.index')->with('error', 'Le jeu en question n\'a pas été trouvé en base de données');
        }
        $owners = $game->owners;

        //TODO purger les champs confidentiels des users
        
        return view('game.details', [
            'game'          => $game,
            'owners'        => $owners
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        if (!Auth::check()) {
            dd("Vous êtes déconnecté·e, cette page n'est pas disponible");
        }

        $game = Game::findOrFail($id) ;

        $characteristicsManager = new CharacteristicManager ;

        return view('game.edit', [
            'game'                      => $game,
            'gameTypesList'             => $characteristicsManager->getTypesList(),
            'gameAffrontementsList'     => $characteristicsManager->getAffrontementsList(),
            'gameFormatsList'           => $characteristicsManager->getFormatsList(),
            'gameCapacitesList'         => $characteristicsManager->getCapacitesList(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\GameRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(GameRequest $request, $id) {
        if (!Auth::check()) {
            dd("Vous êtes déconnecté·e, cette page n'est pas disponible");
        }

        $validatedData = $request->validated() ;
        
        if($request->hasFile('file')) {
            // Upload file
            $file = $request->file;
            $filename = Str::slug($validatedData['title'], '_') . '.' . $file->extension() ;
            $location = 'img/games_covers/';
            $file->move($location,$filename);

            $validatedData['illustration'] = $filename ;
        }

        $theGame = Game::findOrFail($id);
        //dd($validatedData);
        $theGame->update($validatedData);

        return redirect()->route('games.show', $theGame->slug)->with('success', 'Le jeu a bien été modifié');
    }

    /**
     * Soft delete the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        if (!Auth::check()) {
            dd("Vous êtes déconnecté·e, cette page n'est pas disponible");
        }

        $game = Game::findOrFail($id) ;
        $game->update([
            'deleted_at'    => now(),
            'is_available'  => 0
        ]);
        return redirect()->route('games.index')->with('success', 'Le jeu a bien été supprimé');
    }


    /* ---------------------------------------------------------------------------------- */
    /** 
    * @param  Illuminate\Http\Request $request
    */
    public function searchGames(Request $request) {
        return response()->json([
            'games' => $games
        ]);
    }

    
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/game/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h1>
            {{ __('Ajouter un jeu') }}
        </h1>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <form class="form_container" action="{{ route('games.store')}}" method="POST"  enctype="multipart/form-data">
                        @csrf
                        <div class="form_row">
                            <div class="form_col-25"><label for="title" required>Titre</label></div>
                            <div class="form_col-75"><input id="title" name="title" type="text" class="form-input @error('title') is-invalid @enderror" required /></div>
                            @error('title')
                                {{ $message }}
                            @enderror
                        </div>

                        <div class="form_row">
                            <div class="form_col-25"><label for="shortdescription">Principe</label></div>
                            <div class="form_col-75"><textarea id="shortdescription" name="shortdescription" maxlength="255"></textarea></div>
                            @error('')
                                {{ $message }}
                            @enderror
                        </div>

                        <div class="form_row">
                            <div class="form_col-25"><label for="nbPlayers" required>Nb de joueurs min</label></div>
                            <div class="form_col-75"><input id="nbplayers_min" name="nbplayers_min" type="number" class="form-input" required /></div>
                            @error('nbplayers_min')
                                {{ $message }}
                            @enderror
                        </div>

                        <div class="form_row">
                            <div class="form_col-25"><label for="nbPlayers" required>Nb de joueurs max</label></div>
                            <div class="form_col-75"><input id="nbplayers_max" name="nbplayers_max" type="number" class="form-input" required /></div>
                            @error('nbplayers_max')
                                {{ $message }}
                            @enderror
                        </div>
                        
                        <div class="form_row">
                            <div class="form_col-25"><label for="minimalage">Âge minimum</label></div>
                            <div class="form_col-75"><input id="minimalage" name="minimalage" type="number" class="form-input" /></div>
                            @error('')
                                {{ $message }}
                            @enderror
                        </div>
                        
                        <div class="form_row">
                            <div class="form_col-25"><label for="format">Format de jeux</label></div>
                            <div class="form_col-75"><select name="format" id="format">
                                <option></option>
                                @foreach ($gameFormatsList as $item)
                                    <option>{{ $item->label }}</option>
                                @endforeach
                            </select></div>
                            @error('')
                                {{ $message }}
                            @enderror
                        </div>
                        
                        <div class="form_row">
                            <div class="form_col-25"><label for="affrontementtype">Système d'affrontement</label></div>
                            <div class="form_col-75"><select name="affrontementtype" id="affrontementtype">
                                <option></option>
                                @foreach ($gameAffrontementsList as $item)
                                    <option>{{ $item->label }}</option>
                                @endforeach
                            </select></div>
                            @error('')
                                {{ $message }}
                            @enderror
                        </div>
                        
                        <div class="form_row">
                            <div class="form_col-25"><label for="type">Type</label></div>
                            <div class="form_col-75"><select name="type" id="type">
                                <option></option>
                                @foreach ($gameTypesList as $item)
                                    <option>{{ $item->label }}</option>
                                @endforeach
                            </select></div>
                            @error('')
                                {{ $message }}
                            @enderror
                        </div>
                        
                        <!--div class="form_row">
                            <div class="form_col-25"><label for="capacityneeded">Capacités mises en jeu</label></div>
                            <div class="form_col-75">
                                @foreach ($gameCapacitesList as $item)
                                    <input type="checkbox" name="capacityneeded[]" id="{{ $item->label }}" value="{{ $item->label }}" /> <label for="{{ $item->label }}">{{ $item->label }}</label>
                                @endforeach
                            </div>
                            @error('')
                                {{ $message }}
                            @enderror
                        </div-->

                        <div class="form_row">
                            <div class="form_col-25"><label for="durationgame">Durée</label></div>
                            <div class="form_col-75"><input id="durationgame" name="durationgame" type="text" value="00:30:00"/></div>
                            @error('')
                                {{ $message }}
                            @enderror
                        </div>
                        
                        <div class="form_row">
                            <div class="form_col-25"></div>
                            <div class="form_col-75"><input type="checkbox" name="is_gamemasterneeded" id="is_gamemasterneeded" value="1" /> <label for="is_gamemasterneeded">Maître du jeu nécessaire</label></div>
                            @error('')
                                {{ $message }}
                            @enderror
                        </div>
                        
                        <div class="form_row">
                            <div class="form_col-25"><label for="rules_text">Règles</label></div>
                            <div class="form_col-75"><textarea id="rules_text" name="rules_text" class="contentEditor"></textarea></div>
                            @error('')
                                {{ $message }}
                            @enderror
                        </div>
                        
                        <div class="form_row">
                            <div class="form_col-25"><label for="rules_video">Règles en vidéo (lien) :</label></div>
                            <div class="form_col-75"><input id="rules_video" name="rules_video" type="text"/></div>
                            @error('')
                                {{ $message }}
                            @enderror
                        </div>
                        <div class="form_row">
                            <div class="form_col-25"><label for="file">Illustration</label></div>
                            <div class="form_col-75"><input type="file" id="file" name="file" accept="image/png, image/jpeg"></div>
                            @error('file')
                                {{ $message }}
                            @enderror
                        </div>
                        
                        <div class="form_row">
                            <div class="form_col-25"><label for="content">Contenu de base</label></div>
                            <div class="form_col-75"><textarea id="content" name="content" class="contentEditor"></textarea></div>
                            @error('')
                                {{ $message }}
                            @enderror
                        </div>
                        
                        <div class="form_row">
                            <div class="form_col-25"></div>
                            <div class="form_col-75"><input type="checkbox" name="is_available" id="is_available" value="1" checked /> <label for="is_available">Disponible</label></div>
                            @error('')
                                {{ $message }}
                            @enderror
                        </div>

                        <div class="form_row">
                            <input type="submit" value="Ajouter" />
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/game/details.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-wrap items-center">
            <h1 class="mr-2">
                {{ __('Détails de '.$game->title) }}
            </h1>
            @if (Auth::user() !== null)
                <!-- Suppression -->
                <form method="POST" action="{{ route('games.destroy', $game) }}">
                    @csrf
                    @method('DELETE')
                    <button class="delete" type="submit">Supprimer</button>
                </form>
                <a href="{{ route('games.edit', $game) }}" class="button" />Modifier</a>
            @endif
        </div>
        <div class="">
            <div class="">
                <img src="/img/games_covers/{{ $game->illustration }}" alt="" class="illustration inset-0 w-full h-full object-cover rounded-lg" />
                @if (Auth::user() !== null)
                    <div class="">
                        <p>Possédé par :</p>
                        @foreach ($owners as $anOwner)
                            <img src="/img/users_avatars/{{ $anOwner->avatar }}" alt="" title="{{ $anOwner->name }} {{ false ? "(emprunté par quelqu'un·e)" : "" }}" class="minivignette inset-0 w-full h-full object-cover rounded-lg {{ $game->is_available !== 1 ? "unavailable" : "" }}" />
                        @endforeach
                    </div>
                @endif
            </div>
            <div>
                {{ $game->format }} ({{ $game->type }}) {{ $game->affrontementtype }} {{ $game->capacityneeded }}
                <p><span class="ml-3 text-sm text-gray-500 underline">Nb de joueurs :</span> {{ $game->nbplayers_min }} -> {{ $game->nbplayers_max }} ({{ $game->minimalage }} ans minimum)</p>
                <p><span class="ml-3 text-sm text-gray-500 underline">Durée :</span> {{ $game->durationgame }}</p>
                <p><span class="ml-3 text-sm text-gray-500 underline">Présentation :</span> {{ $game->shortdescription }}</p>
                @if ($game->is_gamemasterneeded === 1)
                <p>Nécessite un·e Maître Du Jeu</p>
                @endif
                <span class="ml-3 text-sm text-gray-500 underline">Règle :</span> {{ $game->rules_text }}
                <p><span class="ml-3 text-sm text-gray-500 underline"><a href="{{ $game->rules_video }}">Règle (vidéo)</a></span> </p>
                <span class="ml-3 text-sm text-gray-500 underline">Contenu du jeu :</span> {{ $game->content }}
            </div>

            <a href="{{ route('games.index') }}" title="Revenir à la liste" class="button" />Retour à la liste</a>
        </div>
    </x-slot>

</x-app-layout>